name: Run tests on Pull Request or Push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.5'

      - name: Run test against code
        run: make